### ISSUE TITLE
no readme

### ISSUE THREAD

**Issue by noraj** [SniperOJ/Platform#2]
can you provide a README with a description, how to install it, etc.

**Comment by WangYihang** [comment]
This platform is written in PHP before, this repo is a testing repo. so It cannot be deployed. sorry, bro.
and the PHP version is a little primitive... (even there is no admin panel) so If you want to host a CTF game, this platform is not prepared for you. you can try CTFd and other CTF platforms.

**Comment by WangYihang** [comment]
And, if you just wanna practice your ctf skills, you can see these repos
(You can deploy all challenges with docker-compose, highly recommend):
Dockerfiles
> https://github.com/SniperOJ/Dockerfiles

and all write-ups in this repo:
> https://github.com/SniperOJ/Writeups

**Comment by noraj** [comment]
I created a README template https://github.com/SniperOJ/Platform/pull/3

**Comment by WangYihang** [comment]
Thank you bro, Look at this: https://github.com/SniperOJ/Platform/pull/3#issuecomment-432032573
